version: "3.8"

services:
  # Builds the frontend Docker image and creates the frontend microservice
  nyagaah-yolo-client:
    image: nyagaah/yolo_app:1.0
    build: ./client
    container_name: nyagaah-yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - nyagaah-yolo-backend
    networks:
      - app-net

  # Builds the backend Docker image and creates the backend microservice
  nyagaah-yolo-backend:
    image:nyagaah/yolo_app:1.0
    build: ./backend
    container_name: nyagaah-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-mongo
    networks:
      - app-net

  # Creates the database microservice
  app-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - app-mongo-data:/data/db

# Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app-net:

# Creates a Docker volume that persists all the data stored in the database
volumes:
  app-mongo-data:
    driver: local
