services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/yolo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:4.4
    container_name: yolo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
