---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    # Ansible/playbook.yml
---
- name: Provision resources with Terraform
  terraform:
    project_path: "{{ terraform_dir }}"
    state: present

- name: Configure server with Ansible
  ansible:
    playbook: "{{ ansible_dir }}/playbook.yml"
    inventory: "{{ ansible_dir }}/inventory"