apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image:  brianbwire/brian-yolo-client:v1.0.0
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: http://backend.default.svc.cluster.local:80
      restartPolicy: Always
  strategy:
    type: Recreate