# roles/backend/tasks/main.yml
- name: Build and run the backend container
  docker_container:
    name: "{{brian-yolo-backend  }}_backend"
    image: "{{ brianbwire/brian-yolo-backend:v1.0.0 }}"
    state: started
    ports:
      - "{{ backend_port }}:8000"  # Map the backend port
    restart_policy: always
    volumes:
      - ./backend:/app  # Mount local directory to the container
